parameters:
#    fd_mon_premier.example.class: FD\MonPremierBundle\Example

services:
#    fd_mon_premier.example:
#        class: %fd_mon_premier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
